DATA:
  BATCH_SIZE: 256
  DATASET: imagenet
  DATA_PATH: /home/ubuntu/work/oneflow/datasets
  IMG_SIZE: 224
  INTERPOLATION: bicubic
  ZIP_MODE: False
  CACHE_MODE: "part"
  PIN_MEMORY: True
  NUM_WORKERS: 8

MODEL:
  PRETRAINED: False
  RESUME: ""
  LABEL_SMOOTHING: 0.1

TRAIN:
  START_EPOCH: 0
  EPOCHS: 300
  WARMUP_EPOCHS: 3
  WARMUP_LR: 0.0001
  MIN_LR: 1.0e-06
  WEIGHT_DECAY: 2.0e-05
  BASE_LR: 0.01
  CLIP_GRAD: None
  AUTO_RESUME: True
  ACCUMULATION_STEPS: 0
  
  LR_SCHEDULER:
    NAME: cosine
    MILESTONES: None

  OPTIMIZER:
    NAME: sgd
    MOMENTUM: 0.9
    NESTEROV: True

  
AUG:
  COLOR_JITTER: 0.4
  AUTO_AUGMENT: rand-m9-mstd0.5-inc1
  REPROB: 0.6
  REMODE: pixel
  RECOUNT: 1
  MIXUP: 0.
  CUTMIX: 0.
  CUTMIX_MINMAX: None

TEST:
  CROP: True
  SEQUENTIAL: False

TAG: default
SAVE_FREQ: 1
PRINT_FREQ: 10
SEED: 42
EVAL_MODE: False
THROUGHPUT_MODE: False
