name: Document Release

on:
  push:
    branches:
      - main

jobs:
  API_Document_Release:
    name: API Document Release
    runs-on: ubuntu-20.04
    steps:
    - name: Syncing the webhook
      env:
        FLOWVISION_READTHEDOCS_TOKEN: ${{ secrets.FLOWVISION_READTHEDOCS_TOKEN }}
      run: |
        curl -X POST -d "branches=main" -d "token=${FLOWVISION_READTHEDOCS_TOKEN}"  https://readthedocs.org/api/v2/webhook/flowvision/187769/
