name: Document Release

on:
  push:
    branches:
      - main

jobs:
  API_Document_Release:
    name: API Document Release
    runs-on: ubuntu-18.04
    steps:
    - name: Syncing the webhook
      env:
        READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
      run: |
        curl -X POST -d "branches=main" -d "token=${READTHEDOCS_TOKEN}"  https://readthedocs.org/api/v2/webhook/flowvisiontest/187702/