name: API Document Release

on: push

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-18.04
    steps:
    - name: Run a single-line script
      run: |
        curl -X POST -d "branches=main" -d "token=${READTHEDOCS_TOKEN}"  readthedocs.org/api/v2/webhook/flowvisiontest/187665/