name: API Document Release

on: push

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-18.04
    steps:
    - name: Run a single-line script
      run: |
        curl -X POST -d "branches=master" -d "token=${READTHEDOCS_TOKEN}"  https://readthedocs.org/api/v2/webhook/oneflow/135376/