name: Document Release

on: push

jobs:
  API_Document_Release:
    name: API Document Release
    runs-on: ubuntu-18.04
    steps:
    - name: Syncing the webhook script
      env:
        READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
      run: |
        curl -X POST -d "branches=main" -d "token=${READTHEDOCS_TOKEN}"  readthedocs.org/api/v2/webhook/flowvisiontest/187665/